### ISSUE TITLE
The Cheese Looks improper to Prime's cheese.

### ISSUE THREAD

**Issue by AshtonSparx** [EIA485/NeosCheese4All#1]
![image](https://user-images.githubusercontent.com/53165730/140605897-45c7465d-6db8-443a-b1f5-0e26099daf0d.png)

The cheese curser looks fine on Prime's videos youtube tutorials. But mine has a weird line on the tip.

![image](https://user-images.githubusercontent.com/53165730/140605912-9d25519c-a93a-496b-8d60-995078d15531.png)

**Comment by EIA485** [comment]
fixed in version 1.1.0.0
